# Generated by Django 4.2.8 on 2024-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
